version: '3.2'

services:
  php-cli-resource-crawler-swoole:
    container_name: php-cli-resource-crawler-swoole
    build:
      context: php-cli
      args:
        - USER_ID=${USER_ID-1000}
        - GROUP_ID=${GROUP_ID-1000}
    volumes:
      - ../../:/var/www/resource-crawler-swoole
      - /var/www/resource-crawler-swoole/.git
      - /var/www/resource-crawler-swoole/.idea
      - /var/www/resource-crawler-swoole/infrastructure
    tty: true
    ports:
      - "80:9000"
    expose:
      - 9003
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
      PHP_IDE_CONFIG: "serverName=localhost"
      XDEBUG_MODE: "develop,debug"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003 start_with_request=yes"
