version: '3.2'

services:
  php-cli-resource-crawler-swoole:
    container_name: php-cli-resource-crawler-swoole
    build:
      context: php-cli
      args:
        - USER_ID=${USER_ID-1000}
        - GROUP_ID=${GROUP_ID-1000}
    volumes:
      - ../../server:/var/www/resource-crawler-swoole/server
    tty: true
    ports:
      - "80:9000"

  node-resource-crawler-swoole:
    container_name: node-resource-crawler-swoole
    build:
      context: node
      args:
        - USER_ID=${USER_ID-1000}
        - GROUP_ID=${GROUP_ID-1000}
    volumes:
      - ../../client:/var/www/resource-crawler-swoole/client
      - ../../server/public/resources:/var/www/resource-crawler-swoole/server/public/resources
    tty: true
    ports:
      - "8080:9000"
